/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Cookie = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Text,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'role' : IDL.Text,
  'text' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'getAllCookies' : IDL.Func([], [IDL.Vec(Cookie)], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getCookieById' : IDL.Func([IDL.Nat], [IDL.Opt(Cookie)], ['query']),
  'sendChatMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Cookie = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Text,
  });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'role' : IDL.Text,
    'text' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'getAllCookies' : IDL.Func([], [IDL.Vec(Cookie)], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getCookieById' : IDL.Func([IDL.Nat], [IDL.Opt(Cookie)], ['query']),
    'sendChatMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };